#!/usr/bin/env node
// LAB-2's §3.6 deliverable: binned transfer function, fan width, timing sensitivity, Pareto
// front, cradle rate + vo/vi gradient, and the recommendation paragraph. Reads Stage B's
// main-family run (24 geometries x the 42-point policy sweep) and its cradle-family run
// (24 geometries, `pol:'heldActive'`), streams every shard once, and writes
// `data/summaries/e1-lab2-<runId>.{json,md}`.
//
//   node src/lab2Report.js --stageB <dir> --cradle <dir> --out <runId>
import { readFileSync, writeFileSync, createReadStream } from 'node:fs';
import { createGunzip } from 'node:zlib';
import readline from 'node:readline';
import path from 'node:path';
import { mean, sd, percentile } from './metrics.js';
import { cfgId as hashCfg } from './sweep.js';
import { rankingValidityResult, premiseHeaderLines, requireFlagGateOk } from './gate.js';
import { rate as measuredRate, fmt as fmtMeasured } from './measured.js';

const GEOMETRY_KEYS = ['restAngleDeg', 'activeAngleDeg', 'upMs', 'omegaProfile', 'radius', 'restitution'];
const HS_BINS = 10;
const PHASES = ['rest', 'rising', 'full', 'returning'];
const VI_BINS = 6, VI_MAX = 6.0; // m/s
const AI_BINS = 8, AI_MAX = 360; // deg
const CRADLE_SETTLE_WINDOW_S = 1.5; // §3.5: "reaches |v|<0.05 ... within 1.5 s"
// RETIRE-ALL §3/§4 (ledger/handoffs/opus2/20260905T201139Z-decisions.md): `timingSensitivityDegPerMs`,
// `SENSITIVITY_CEILING` and the Pareto front built from them are retired from this file's PUBLISHED
// output — see the doc comment above the dominance-exclusion computation below for why, and what
// replaces them. Retiring is a source-code decision recorded here; it does not by itself change any
// already-published summary (no summary is regenerated by this dispatch).
const DOMINANCE_RESAMPLES = 150; // see computeDominanceExclusion's own doc comment

/** Pure per-geometry summary over one cradle cfg's full record set — pulled out of the
 * streaming loop below so it can be unit-tested with a synthetic record array instead of a
 * real run. `records`: every trial's raw record for one geometry's cradle cfg (`{cr, st, bn,
 * cs}`, the fields `instrument.js`'s runE1Trial writes on cradle-family trials).
 * `csMedianMps` (ledger/handoffs/opus2/20260904T150000Z-three-gate-rulings.md §(a), pilot
 * confirmed in ledger/handoffs/sonnet2/20260904T160000Z-cradle-continuous-stat-pilot.md):
 * median of `cs` (min ball speed while touching a flipper) across every CONTACTING trial, not
 * just settled ones — cradleRate's own denominator is `trials`, not `settled`, and this column
 * is reported alongside it, not used to select anything (Stage A selection is unchanged; see
 * that pilot handoff). `cs === null` on any trial that never contacted a flipper. */
export function cradleRowStats(records) {
  let trials = 0, settled = 0;
  const settleTimes = [], bounces = [], csVals = [];
  for (const r of records) {
    trials += 1;
    if (r.cs !== null && r.cs !== undefined) csVals.push(r.cs);
    if (r.cr === 1 && r.st !== null && r.st <= CRADLE_SETTLE_WINDOW_S) {
      settled += 1;
      settleTimes.push(r.st);
      bounces.push(r.bn);
    }
  }
  return {
    trials, settled,
    cradleRate: trials > 0 ? settled / trials : null,
    settleTimeMeanS: settleTimes.length ? mean(settleTimes) : null,
    bouncesMean: bounces.length ? mean(bounces) : null,
    csMedianMps: csVals.length ? percentile(csVals, 50) : null,
  };
}

function geometryOf(cfg) {
  const g = {};
  for (const k of GEOMETRY_KEYS) g[k] = cfg[k];
  return g;
}
function geomLabel(g) {
  return `rest=${g.restAngleDeg}° active=${g.activeAngleDeg}° up=${g.upMs}ms ${g.omegaProfile} r=${g.radius}m e=${g.restitution}`;
}

async function* streamShards(runDir, cfgMeta) {
  for (const shard of cfgMeta.shards) {
    const rl = readline.createInterface({ input: createReadStream(path.join(runDir, shard.path)).pipe(createGunzip()) });
    for await (const line of rl) {
      if (line.trim()) yield JSON.parse(line);
    }
  }
}

function binIndex(v, bins, max, min = 0) {
  if (v === null || v === undefined || !Number.isFinite(v)) return null;
  const width = (max - min) / bins;
  let idx = Math.floor((v - min) / width);
  if (idx < 0) idx = 0;
  if (idx >= bins) idx = bins - 1;
  return idx;
}

function newLinReg() {
  return { n: 0, sx: 0, sy: 0, sxy: 0, sxx: 0 };
}
function addLinReg(r, x, y) {
  r.n += 1; r.sx += x; r.sy += y; r.sxy += x * y; r.sxx += x * x;
}
function slopeOf(r) {
  if (r.n < 2) return null;
  const denom = r.n * r.sxx - r.sx * r.sx;
  if (denom === 0) return null;
  return (r.n * r.sxy - r.sx * r.sy) / denom;
}

// --- deterministic PRNG for the bootstrap below (same tiny primitive selectTopN.js uses, not
// imported from there per this dispatch's own instruction not to migrate anything to that
// module — duplicated rather than shared). Seeded from the data, not passed in, so a re-run
// reproduces the same exclusion set rather than shopping for a seed. ---
function fnv1a(str) {
  let h = 0x811c9dc5;
  for (let i = 0; i < str.length; i++) { h ^= str.charCodeAt(i); h = Math.imul(h, 0x01000193); }
  return h >>> 0;
}
function mulberry32(seed) {
  let a = seed >>> 0;
  return () => {
    a |= 0; a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
function resampleWithReplacement(arr, rng) {
  const out = new Array(arr.length);
  for (let i = 0; i < arr.length; i++) out[i] = arr[Math.floor(rng() * arr.length)];
  return out;
}

/**
 * RETIRE-ALL §3 (decision doc, ledger/handoffs/opus2/20260905T201139Z-decisions.md; corrected by
 * the operator's own follow-up, RETIRE-ALL-C): the Pareto front is retired, not merely annotated.
 * §4's retirement of `timingSensitivityDegPerMs` as a trustworthy per-geometry measurement means
 * there is no longer a second published axis to build a front from at all — dominance needs two
 * axes, and this file now asserts only one. "No front can be computed" is a structural fact, not
 * a data-quality caveat.
 *
 * What replaces it, per RETIRE-ALL-C: not a silent removal, but the exclusion — which of the 24
 * geometries are reliably dominated is a real, useful finding that survives the front's own
 * retirement (opus2's own bootstrap found 14 of 24 excluded at <5% front-inclusion frequency,
 * 0 confirmed at >=95%; ledger/handoffs/opus2/20260905T135010Z-guarded-dominance.md). That
 * dispatch reported COUNTS, not which 24 geometries they are — "name them" (RETIRE-ALL-C) needs
 * the actual keys, so this function recomputes the exclusion here, from the same raw fan-width
 * samples this file already streams.
 *
 * Deliberately NOT a full two-axis bootstrap reproducing opus2's own numbers exactly: resampling
 * the sensitivity axis honestly requires bootstrapping the raw per-delay-bin trial values (this
 * file currently only keeps their SUMS, per geometry, not the arrays), which is a larger
 * refactor than this dispatch's own scope. Instead this uses the axis's already-computed POINT
 * ESTIMATE (still available internally, never published — see the caller) as a fixed filter
 * alongside a real bootstrap on fan width alone. This is honest about being a narrower
 * approximation, not a re-derivation of opus2's exact figures, and is expected to find an
 * exclusion count in the same neighbourhood, not identical to the 14 already reported — stated
 * plainly in the handoff, not claimed as a byte-for-byte reproduction.
 *
 * `geoms`: per-geometry {geometryKey, xaVals, sensitivityPoint} — `xaVals` is the same shotline-
 * filtered array already collected for fanWidthXaDeg; `sensitivityPoint` is the (unpublished)
 * point-estimate timing sensitivity, used only as a static tie-breaker in the dominance test,
 * never resampled itself (that is exactly the axis's own defect this retirement is about).
 * Returns `{ excluded: [keys], excludedCount, total, resamples, seed }` — no `front` field, ever
 * (same anti-V2 discipline as `selectTopN`'s own tagged union: a retired claim has no field to
 * accidentally publish under its old name).
 */
function computeDominanceExclusion(geoms, resamples = DOMINANCE_RESAMPLES) {
  const withFanWidth = geoms.filter((g) => g.xaVals.length >= 2 && g.sensitivityPoint !== null);
  const seed = fnv1a(JSON.stringify(withFanWidth.map((g) => [g.geometryKey, g.xaVals.length]).sort()));
  const dominatedCount = new Map(withFanWidth.map((g) => [g.geometryKey, 0]));
  for (let r = 0; r < resamples; r++) {
    const draws = withFanWidth.map((g) => {
      const rng = mulberry32(fnv1a(`${seed}|${g.geometryKey}|${r}`));
      const sample = resampleWithReplacement(g.xaVals, rng);
      return { geometryKey: g.geometryKey, fanWidth: percentile(sample, 95) - percentile(sample, 5), sensitivityPoint: g.sensitivityPoint };
    });
    for (const i of draws) {
      const dominated = draws.some((j) =>
        j.geometryKey !== i.geometryKey &&
        j.fanWidth >= i.fanWidth && j.sensitivityPoint <= i.sensitivityPoint &&
        (j.fanWidth > i.fanWidth || j.sensitivityPoint < i.sensitivityPoint)
      );
      if (dominated) dominatedCount.set(i.geometryKey, dominatedCount.get(i.geometryKey) + 1);
    }
  }
  const excluded = withFanWidth
    .map((g) => ({ geometryKey: g.geometryKey, dominatedFraction: dominatedCount.get(g.geometryKey) / resamples }))
    .filter((g) => g.dominatedFraction >= 0.95)
    .sort((a, b) => b.dominatedFraction - a.dominatedFraction);
  return {
    excluded: excluded.map((g) => g.geometryKey),
    excludedDetail: excluded,
    excludedCount: excluded.length, total: withFanWidth.length, resamples, seed,
    method: 'fan-width bootstrap x sensitivity point-estimate filter — an approximation of a full two-axis bootstrap, see this function\'s own doc comment',
  };
}

async function main() {
  const args = Object.fromEntries(
    process.argv.slice(2).reduce((pairs, arg, i, arr) => {
      if (arg.startsWith('--')) pairs.push([arg.slice(2), arr[i + 1]]);
      return pairs;
    }, [])
  );
  const stageBDir = args.stageB;
  const cradleDir = args.cradle;
  const runId = args.out;
  if (!stageBDir || !cradleDir || !runId) {
    console.error('usage: node src/lab2Report.js --stageB <dir> --cradle <dir> --out <runId> [--geometryOrigin <ranking.json>]');
    process.exitCode = 1;
    return;
  }

  // RETIRE-ALL §2: optional provenance for the "best" geometry — which of Stage A's two selection
  // halves (§1) it actually entered the candidate pool through. Reads the SAME shape Stage A's own
  // `ranking.json` already writes (`topByFanWidth`/`topByCradle`, arrays of geometryKey), so no new
  // file format is introduced; omit the flag and this file behaves exactly as before (additive).
  const originPath = args.geometryOrigin;
  let origin = null;
  if (originPath) {
    const originData = JSON.parse(readFileSync(originPath, 'utf8'));
    origin = { topByFanWidth: new Set(originData.topByFanWidth ?? []), topByCradle: new Set(originData.topByCradle ?? []) };
  }
  function originOf(key) {
    if (!origin) return null;
    const inFw = origin.topByFanWidth.has(key), inCr = origin.topByCradle.has(key);
    if (inFw && inCr) return 'both';
    if (inFw) return 'fanWidth';
    if (inCr) return 'cradle';
    return 'unknown';
  }

  const stageBMeta = JSON.parse(readFileSync(path.join(stageBDir, 'meta.json'), 'utf8'));
  const cradleMeta = JSON.parse(readFileSync(path.join(cradleDir, 'meta.json'), 'utf8'));

  // --- Per-geometry accumulators ---
  const geoms = new Map(); // geomKey -> { geometry, xaVals: [], byDelay: Map(d -> {n,sum}), gradReg, transferAcc-scoped separately }
  const transferBins = new Map(); // key "hs|phase|vi|ai" -> {n, sumVo, sumSqVo, sumAo, sumSqAo}
  let totalTrials = 0, totalFlagged = 0, totalContacted = 0, totalShotline = 0;
  const impactsExhausted = 1, escaped = 2, timeoutFlag = 4, stalled = 8, nanFlag = 16;
  const flagCounts = { IMPACTS_EXHAUSTED: 0, ESCAPED: 0, TIMEOUT: 0, STALLED: 0, NAN: 0 };

  for (const cfgMeta of stageBMeta.cfgs) {
    const cfg = cfgMeta.cfg;
    const gKey = hashCfg(geometryOf(cfg));
    let g = geoms.get(gKey);
    if (!g) {
      g = { geometryKey: gKey, geometry: geometryOf(cfg), xaVals: [], byDelay: new Map(), gradReg: newLinReg(), trials: 0, flagged: 0, contacted: 0 };
      geoms.set(gKey, g);
    }
    for await (const r of streamShards(stageBDir, cfgMeta)) {
      totalTrials += 1;
      g.trials += 1;
      if (r.f !== 0) { totalFlagged += 1; g.flagged += 1; }
      if (r.f & impactsExhausted) flagCounts.IMPACTS_EXHAUSTED += 1;
      if (r.f & escaped) flagCounts.ESCAPED += 1;
      if (r.f & timeoutFlag) flagCounts.TIMEOUT += 1;
      if (r.f & stalled) flagCounts.STALLED += 1;
      if (r.f & nanFlag) flagCounts.NAN += 1;

      const contacted = r.vi !== null;
      if (contacted) {
        totalContacted += 1;
        g.contacted += 1;
        // §2.7 / P0-2 (LAB-11): "flagged trials are excluded from distributions" — LAB-2's own
        // handoff claimed this for the transfer function and gradient but the code never
        // checked `r.f`, only `term`/`contacted` (which only screens NAN/ESCAPED/TIMEOUT/
        // STALLED as a side effect of those flags always `break`-ing with their own term;
        // IMPACTS_EXHAUSTED sets its flag WITHOUT breaking, so it silently rode along).
        // `contacted`/`totalContacted`/`contactRate` themselves are left as "contacted at
        // all" (unchanged meaning) — only the distributions the fix is actually about are
        // gated here.
        if (r.f === 0) {
          // Transfer function bin (§3.6.1): (hs x phase x vi x ai) -> (vo, ao).
          const hsIdx = binIndex(r.hs, HS_BINS, 1);
          const phaseIdx = PHASES.indexOf(r.hp);
          const viIdx = binIndex(r.vi, VI_BINS, VI_MAX);
          const aiIdx = binIndex(r.ai, AI_BINS, AI_MAX);
          if (hsIdx !== null && phaseIdx >= 0 && viIdx !== null && aiIdx !== null) {
            const key = `${hsIdx}|${phaseIdx}|${viIdx}|${aiIdx}`;
            let b = transferBins.get(key);
            if (!b) { b = { n: 0, sumVo: 0, sumSqVo: 0, sumAo: 0, sumSqAo: 0 }; transferBins.set(key, b); }
            b.n += 1; b.sumVo += r.vo; b.sumSqVo += r.vo * r.vo; b.sumAo += r.ao; b.sumSqAo += r.ao * r.ao;
          }
          // §3.5's secondary heaviness signal: gradient of vo/vi along hs, pooled across phase
          // (documented approximation — the spec asks "at fixed phase"; pooling all contacted
          // trials for one geometry keeps the sample size usable at Stage B resolution).
          if (r.vi > 0) addLinReg(g.gradReg, r.hs, r.vo / r.vi);
        }
      }
      // P0-2: fan width / timing-sensitivity is the OTHER distribution LAB-2's handoff claimed
      // was flag-filtered ("computed only from shotline trials") but wasn't — `term ===
      // 'shotline'` alone doesn't exclude a trial that also set IMPACTS_EXHAUSTED earlier in
      // the same run (flags accumulate across the whole trial; term is just what broke the loop).
      if (r.term === 'shotline' && r.f === 0 && cfg.pol !== 'never') {
        totalShotline += 1;
        g.xaVals.push(r.xa);
        if (cfg.pol === 'fixedDelay') {
          let d = g.byDelay.get(cfg.d);
          if (!d) { d = { n: 0, sum: 0 }; g.byDelay.set(cfg.d, d); }
          d.n += 1; d.sum += r.xa;
        }
      }
    }
  }

  // LAB-28 (V4): `totalTrials ? x / totalTrials : 0` below would read a zero-trial run (an
  // empty --stageB cfg set, or every shard failing to stream) as a measured, clean 0% flagged —
  // identical to gate.js's own zero-trials principle (`flagGateResult`, `rankingValidityResult`)
  // that a corpus with no trials carries no statistical power and must not read as passing.
  // Refused here, before any number derived from `totalTrials` is computed, rather than
  // threading a `null` sentinel through every `* 100` in the markdown below.
  if (totalTrials === 0) {
    throw new Error(`lab2Report: --stageB ${stageBDir} produced zero trials — an empty corpus carries no statistical power and must not be summarised as a clean 0% flagged/contacted run.`);
  }

  // --- Fan width per geometry. Timing sensitivity is computed but NOT published (RETIRE-ALL
  // §4): shuffling the delay labels leaves it statistically unchanged (opus2's own null sweep —
  // observed/null-median ratio 0.983, 0 of 24 geometries exceed their own null's 95th percentile,
  // and a one-way F test finds no delay-dependent structure of any shape). `abs()` applied to
  // each of ~20 local slopes before the median rectifies noise into a stable, reproducible,
  // MEANINGLESS positive number that tracks the bin-mean standard error instead of anything
  // physical. Kept here as `sensitivityPoint`, attached to the internal accumulator only (never
  // pushed into `geometryResults`, never serialized), because computeDominanceExclusion's own
  // approximation still needs it as a static filter — seeing it correctly demoted to "internal
  // diagnostic input, not a trustworthy measurement" is the point of this retirement, not an
  // excuse to delete the arithmetic outright. ---
  const geometryResults = [];
  const sensitivityPointByKey = new Map();
  for (const g of geoms.values()) {
    const fanWidthXa = g.xaVals.length >= 2 ? percentile(g.xaVals, 95) - percentile(g.xaVals, 5) : null;
    const delayPoints = [...g.byDelay.entries()].filter(([, v]) => v.n > 0).sort((a, b) => a[0] - b[0]).map(([d, v]) => [d, v.sum / v.n]);
    const localSlopes = [];
    for (let i = 1; i < delayPoints.length; i++) {
      const [d0, xa0] = delayPoints[i - 1];
      const [d1, xa1] = delayPoints[i];
      if (d1 !== d0) localSlopes.push(Math.abs((xa1 - xa0) / (d1 - d0)));
    }
    sensitivityPointByKey.set(g.geometryKey, localSlopes.length ? percentile(localSlopes, 50) : null);
    const gradient = slopeOf(g.gradReg);
    geometryResults.push({
      geometryKey: g.geometryKey, geometry: g.geometry, label: geomLabel(g.geometry),
      trials: g.trials, flaggedFraction: g.trials > 0 ? g.flagged / g.trials : 0,
      contactRate: g.trials > 0 ? g.contacted / g.trials : 0,
      // MEASURED-3: additive sidecars — the bare fields above are unchanged (this file's own
      // sort/JSON consumers keep reading them as plain numbers). Not rendered as their own
      // markdown columns (neither ever was), so JSON is where these are published.
      flaggedFractionM: measuredRate(g.flagged, g.trials, { estimand: `${g.geometryKey}: fraction of trials carrying any validity flag` }),
      contactRateM: measuredRate(g.contacted, g.trials, { estimand: `${g.geometryKey}: fraction of trials reaching flipper contact` }),
      fanWidthXaDeg: fanWidthXa,
      voViGradientPerHs: gradient, delayPoints,
    });
  }

  // --- Cradle family. RETIRE-ALL §5: cradleRate keeps its own event count alongside it (46
  // settled events total across all 24 geometries, 15 of them at zero) — a mean over 1-10 events
  // (cradleSettleTimeMeanS, cradleBouncesMean) is not withdrawn, but is not trustworthy on its
  // own either, so its own denominator travels with it rather than being implied by a bare
  // number. `settled` was already computed by cradleRowStats and previously discarded here. ---
  const cradleResults = [];
  for (const cfgMeta of cradleMeta.cfgs) {
    const cfg = cfgMeta.cfg;
    const gKey = hashCfg(geometryOf(cfg));
    const records = [];
    for await (const r of streamShards(cradleDir, cfgMeta)) records.push(r);
    cradleResults.push({ geometryKey: gKey, geometry: geometryOf(cfg), ...cradleRowStats(records) });
  }
  const cradleByGeom = new Map(cradleResults.map((c) => [c.geometryKey, c]));
  for (const g of geometryResults) {
    const c = cradleByGeom.get(g.geometryKey);
    g.cradleRate = c?.cradleRate ?? null;
    // MEASURED-3: additive sidecar. `c` is null for a geometry with zero cradle trials, which
    // predates this dispatch and is a wiring condition, not a zero-events measurement — kept as
    // `null` (unmeasured has no zero-trial case to construct from) rather than forced through
    // `measuredRate`, which would throw on n=0 anyway.
    g.cradleRateM = c ? measuredRate(c.settled, c.trials, { estimand: `${g.geometryKey}: fraction of cradle-family trials settling within ${CRADLE_SETTLE_WINDOW_S}s` }) : null;
    g.cradleSettledEvents = c?.settled ?? null;
    g.cradleSettleTimeMeanS = c?.settleTimeMeanS ?? null;
    g.cradleBouncesMean = c?.bouncesMean ?? null;
    g.cradleMinContactSpeedMedianMps = c?.csMedianMps ?? null;
  }

  // RETIRE-ALL §3: the Pareto front is retired (see computeDominanceExclusion's own doc comment
  // for why "no front can be computed" is now structural, not a data-quality caveat) and
  // replaced by the exclusion it identified before being retired — 14 of 24 geometries dominated,
  // per opus2's own bootstrap (this dispatch's own recomputation, a narrower single-axis
  // approximation, is expected to land in the same neighbourhood, not reproduce that figure
  // exactly; see the function's doc comment).
  const dominanceExclusion = computeDominanceExclusion(
    geometryResults.map((g) => ({ geometryKey: g.geometryKey, xaVals: geoms.get(g.geometryKey).xaVals, sensitivityPoint: sensitivityPointByKey.get(g.geometryKey) }))
  );

  // RETIRE-ALL §2/§4: `best` is now a top-1 cut on fan width ALONE, over every characterised
  // geometry — no sensitivity ceiling filters the population first (§4: the ceiling never
  // excluded anything at any point in this corpus's history, and it gated on a statistic that
  // measures noise, so removing it changes the population `best` is drawn from not at all in
  // practice — `withFanWidth` below is numerically identical to the old `rankedUnderCeiling`).
  const withFanWidth = geometryResults.filter((g) => g.fanWidthXaDeg !== null).sort((a, b) => b.fanWidthXaDeg - a.fanWidthXaDeg);
  const fanWidthRankingGuard = rankingValidityResult(withFanWidth.map((g) => g.fanWidthXaDeg), { topN: 1 });
  const best = fanWidthRankingGuard.ok ? (withFanWidth[0] ?? null) : null;

  // --- Binned transfer function, flattened ---
  const transferTable = [...transferBins.entries()].map(([key, b]) => {
    const [hs, phase, vi, ai] = key.split('|').map(Number);
    return {
      hsBin: hs, phase: PHASES[phase], viBin: vi, aiBin: ai,
      hsRange: [hs / HS_BINS, (hs + 1) / HS_BINS],
      viRange: [vi * (VI_MAX / VI_BINS), (vi + 1) * (VI_MAX / VI_BINS)],
      aiRange: [ai * (AI_MAX / AI_BINS), (ai + 1) * (AI_MAX / AI_BINS)],
      n: b.n,
      voMean: b.sumVo / b.n, voSd: b.n > 1 ? Math.sqrt(Math.max(0, (b.sumSqVo - b.n * (b.sumVo / b.n) ** 2) / (b.n - 1))) : 0,
      aoMean: b.sumAo / b.n, aoSd: b.n > 1 ? Math.sqrt(Math.max(0, (b.sumSqAo - b.n * (b.sumAo / b.n) ** 2) / (b.n - 1))) : 0,
    };
  }).sort((a, b) => b.n - a.n);

  const summary = {
    exp: 'e1', stage: 'B', runId,
    generatedAt: new Date().toISOString(),
    stageBRunDir: stageBDir, cradleRunDir: cradleDir,
    stageBMeta: { instrumentCommitSha: stageBMeta.instrumentCommitSha, trialCount: stageBMeta.trialCount, secs: stageBMeta.secs },
    // LAB-22: Stage B declares a §2.7 premise (a pure TIMEOUT tail from §3.3's 0.3 m/s
    // floor against the 2.0s cap); echo it where a reader of the summary will meet it.
    declaredPremise: stageBMeta.declaredPremise ?? null,
    declaredPremiseGate: { fraction: stageBMeta.flaggedFraction, ok: requireFlagGateOk(stageBMeta.flagGateOk, 'lab2Report (--stageB meta.json)') },
    cradleMeta: { trialCount: cradleMeta.trialCount, secs: cradleMeta.secs },
    totals: {
      trials: totalTrials, flagged: totalFlagged, flaggedFraction: totalTrials ? totalFlagged / totalTrials : 0,
      contacted: totalContacted, contactRate: totalTrials ? totalContacted / totalTrials : 0,
      // MEASURED-2: additive sidecar — `contactRate` above is unchanged, this is the one
      // headline scalar in this file's summary line converted this dispatch.
      contactRateM: measuredRate(totalContacted, totalTrials, { estimand: 'fraction of Stage B trials reaching flipper contact' }),
      // MEASURED-3: same treatment for the other totals-level rate published alongside it.
      flaggedFractionM: measuredRate(totalFlagged, totalTrials, { estimand: 'fraction of Stage B trials carrying any validity flag' }),
      shotline: totalShotline, flagCounts,
    },
    geometryCount: geometryResults.length,
    geometries: geometryResults.sort((a, b) => (b.fanWidthXaDeg ?? -1) - (a.fanWidthXaDeg ?? -1)),
    // RETIRE-ALL §3: paretoFront/rankedUnderCeiling/sensitivityCeilingDegPerMs retired — see
    // dominanceExclusion below and computeDominanceExclusion's own doc comment for what replaced
    // them, and withFanWidth just above for why `best`'s population is unchanged in practice.
    dominanceExclusion,
    bestGeometryKey: best?.geometryKey ?? null,
    // RETIRE-ALL §2: null unless --geometryOrigin was supplied (see main()'s own doc comment).
    bestGeometryOrigin: best ? originOf(best.geometryKey) : null,
    fanWidthRankingGuard,
    transferFunction: {
      bins: { hs: HS_BINS, phase: PHASES, vi: { count: VI_BINS, max: VI_MAX }, ai: { count: AI_BINS, max: AI_MAX } },
      table: transferTable,
    },
  };

  const summariesDir = path.join(import.meta.dirname, '..', 'data', 'summaries');
  const jsonOut = path.join(summariesDir, `e1-lab2-${runId}.json`);
  const mdOut = path.join(summariesDir, `e1-lab2-${runId}.md`);
  writeFileSync(jsonOut, JSON.stringify(summary, null, 2));
  writeFileSync(mdOut, toMarkdown(summary, best));

  if (!fanWidthRankingGuard.ok) {
    console.error(JSON.stringify({ warning: 'LAB-16 ranking gate: fanWidthXaDeg cannot rank these geometries — no best geometry named', fanWidthRankingGuard }));
  }

  console.log(JSON.stringify({
    ok: true, geometries: geometryResults.length, trials: totalTrials,
    flagged: totalTrials ? Number((totalFlagged / totalTrials).toFixed(4)) : 0,
    dominanceExcluded: dominanceExclusion.excludedCount, best: best?.geometryKey ?? null,
    out: mdOut,
  }));
}

function fmt(x, digits = 2) {
  if (x === null || x === undefined || !Number.isFinite(x)) return '—';
  return x.toFixed(digits);
}

// LAB-28 (V4): `fmt((x ?? 0) * 100, d)` coerces "not measured" (`null`) to a measured 0% before
// fmt ever sees it. A caller with a value that may be null must scale through this helper.
function fmtPct(x, digits = 1) {
  return fmt(x === null || x === undefined ? null : x * 100, digits);
}

function toMarkdown(summary, best) {
  const lines = [];
  lines.push(`# E1 — LAB-2 flipper transfer function (\`${summary.runId}\`)`);
  lines.push('');
  lines.push(`- **instrument commit**: \`${summary.stageBMeta.instrumentCommitSha}\`  ·  **generated**: ${summary.generatedAt}`);
  lines.push(`- **Stage B trials**: ${summary.totals.trials}  ·  **flagged**: ${(summary.totals.flaggedFraction * 100).toFixed(2)}%  ` +
    `(IMPACTS_EXHAUSTED ${(summary.totals.flagCounts.IMPACTS_EXHAUSTED / summary.totals.trials * 100).toFixed(2)}%, ` +
    `ESCAPED ${(summary.totals.flagCounts.ESCAPED / summary.totals.trials * 100).toFixed(3)}%, ` +
    `TIMEOUT ${(summary.totals.flagCounts.TIMEOUT / summary.totals.trials * 100).toFixed(2)}%, ` +
    `STALLED ${(summary.totals.flagCounts.STALLED / summary.totals.trials * 100).toFixed(2)}%, ` +
    `NAN ${(summary.totals.flagCounts.NAN / summary.totals.trials * 100).toFixed(3)}%)`);
  lines.push(`- **flipper contact rate**: ${fmtMeasured(summary.totals.contactRateM)}  ·  **geometries characterised**: ${summary.geometryCount}`);
  lines.push('');
  // LAB-28 (V3): `declaredPremiseGate` is always constructed in `main()` above (and would have
  // thrown via `requireFlagGateOk` before `summary` even existed if it couldn't be), so a `??`
  // fallback here could only ever mask a wiring bug in a future caller by quietly defaulting to
  // `ok: true` — the exact "absence reads as passed" failure this file exists to prevent.
  lines.push(...premiseHeaderLines(summary.declaredPremise ?? null, summary.declaredPremiseGate));
  lines.push('> §2.7: ESCAPED and NAN are near-zero (no solver artifact); TIMEOUT and' +
    ' IMPACTS_EXHAUSTED dominate the flagged fraction — the same pattern LAB-1b found for the' +
    ' main family (slow-speed injections still falling at the 2.0s cap; the flipper firing' +
    ' near a ball already at the pivot saturating MAX_IMPACTS), understood and not smoothed' +
    ' into the ranking below (fan width/sensitivity are computed only from `shotline` trials).');
  lines.push('');

  lines.push('## Fan width / cradle, per geometry');
  lines.push('');
  // RETIRE-ALL §4: `timingSensitivityDegPerMs` retired from this table (and everywhere else in
  // this file) — shuffling the delay labels leaves it statistically unchanged (opus2's own null
  // sweep: observed/null-median ratio 0.983, 0 of 24 geometries exceed their own null's 95th
  // percentile; a one-way F test finds no delay-dependent structure of any shape). It rectified
  // noise into a stable, reproducible, MEANINGLESS positive number that tracked the bin-mean
  // standard error rather than anything physical — see
  // ledger/handoffs/opus2/20260905T201139Z-decisions.md §4. The conclusion it was used to
  // support (timing is not the binding constraint) is not weakened by retiring it — it is
  // strengthened: "no measurable dependence of exit angle on release delay at this budget" is a
  // firmer statement than a rectified 0.142-0.529 deg/ms ever was.
  lines.push('> `timingSensitivityDegPerMs` (formerly a column here) is RETIRED, not merely ' +
    'hidden — it measures noise, not timing sensitivity (proven by construction: shuffling the ' +
    'delay labels leaves it statistically unchanged). See RETIRE-ALL §4 in ' +
    '`ledger/handoffs/opus2/20260905T201139Z-decisions.md`. The negative result survives: no ' +
    'measurable dependence of exit angle on release delay at this budget — which supports ' +
    '"timing is not the binding constraint" more firmly than the retired figure did.');
  lines.push('');
  // LAB-28 (V2), still true after retirement: sorted by fanWidthXaDeg for readability only — no
  // guard covers this full-population ordering (`fanWidthRankingGuard` below answers a
  // narrower question: whether the top-1 cut is unambiguous, not whether this whole table's
  // order is meaningful).
  lines.push('> Sorted by `fanWidthXaDeg` for readability only — this is not a validated ranking ' +
    '(no guard tests the full population\'s ordering; `fanWidthRankingGuard` below tests only the ' +
    'top-1 cut, a narrower question).');
  lines.push('');
  // MEASURED-3: `cradle%`'s own event count used to need its own column (RETIRE-ALL §5) — the
  // Measured rendering carries it inline now (`k events / n`), so the separate `cradle events`
  // column is folded into this one rather than duplicated. `cradleRateM` is `null` only when a
  // cradle cfg produced zero shard rows at all (a wiring gap, not a zero-events measurement,
  // per the field's own comment above) — rendered as `—`, the pre-existing convention for a
  // genuinely absent value.
  lines.push('| geom | rest° | active° | upMs | ω | r | e | fan(xa)° | cradle% | minCs(m/s) | vo/vi grad | dominated |');
  lines.push('|---|---|---|---|---|---|---|---|---|---|---|---|');
  const excludedSet = new Set(summary.dominanceExclusion.excluded);
  for (const g of summary.geometries) {
    lines.push(
      `| ${g.geometryKey} | ${g.geometry.restAngleDeg} | ${g.geometry.activeAngleDeg} | ${g.geometry.upMs} | ` +
      `${g.geometry.omegaProfile} | ${g.geometry.radius} | ${g.geometry.restitution} | ` +
      `${fmt(g.fanWidthXaDeg, 1)} | ${g.cradleRateM ? fmtMeasured(g.cradleRateM) : '—'} | ` +
      `${fmt(g.cradleMinContactSpeedMedianMps, 3)} | ${fmt(g.voViGradientPerHs, 3)} | ${excludedSet.has(g.geometryKey) ? '✓' : ''} |`
    );
  }
  lines.push('');
  // RETIRE-ALL §5: the cradle-family columns keep their own event count next to them —
  // `cradleRate` clears its null (a thin but real discrimination, per the decision doc), but
  // `cradleSettleTimeMeanS`/`cradleBouncesMean` (not shown as their own columns above; see the
  // JSON summary) are means over as few as 1 event for nine geometries and over ZERO for the
  // other fifteen. Kept, per RETIRE-ALL §5's own instruction ("keep, annotate the forty-six-
  // event support") — not withdrawn, but never readable without the count beside it.
  lines.push('> `cradle%`\'s event count (MEASURED-3: now rendered inline, `k events / n`) — 46 ' +
    'settled events total across all 24 geometries (10,9,7,6,5,4,3,1,1,0×15). `cradleSettleTimeMeanS`/' +
    '`cradleBouncesMean` (JSON summary only, not a column here) are means over these same few-or-' +
    'zero events per geometry and are not a trustworthy per-geometry comparison at this budget — ' +
    'shown in the JSON for completeness, not promoted to a table column. `minCs(m/s)`: median of ' +
    'the minimum ball speed while touching a flipper, across every CONTACTING cradle trial (not ' +
    'just settled ones) — a separate, real measurement (pilot: ' +
    'ledger/handoffs/sonnet2/20260904T160000Z-cradle-continuous-stat-pilot.md), not used to ' +
    'select anything here.');
  lines.push('');
  // RETIRE-ALL §3 (corrected by RETIRE-ALL-C): the Pareto front is retired — not merely
  // annotated — because §4's retirement removes the second axis a front needs; there is no
  // longer a published `timingSensitivityDegPerMs` to build one from. What replaces it is the
  // exclusion the front's own bootstrap already found before being retired: opus2's own analysis
  // (ledger/handoffs/opus2/20260905T135010Z-guarded-dominance.md) found the sensitivity axis's
  // confidence interval WIDER than the entire population's spread on that axis (spread/CI =
  // 0.84x) — it cannot separate any two geometries, which is the structural reason no front can
  // be computed, not merely a data-quality caveat. That dispatch reported 14 of 24 geometries
  // dominated in under 5% of resamples but did not name which 24 they are; the `dominated`
  // column above recomputes that from this file's own raw fan-width samples (a narrower
  // single-axis-bootstrap-plus-point-estimate-filter approximation — see
  // computeDominanceExclusion's own doc comment in the source — expected to land in the same
  // neighbourhood, not reproduce that figure exactly).
  lines.push(
    `> **Pareto front: RETIRED.** No front can be computed — the timing-sensitivity axis a front ` +
    `needs has itself been retired (§4: its confidence interval is wider than the whole ` +
    `population's spread on that axis, so it cannot separate any two geometries). What survives ` +
    `is the exclusion: **${summary.dominanceExclusion.excludedCount} of ${summary.dominanceExclusion.total} ` +
    `geometries are dominated** (marked ✓ above) in ${(summary.dominanceExclusion.resamples)} ` +
    `fan-width resamples, ${summary.dominanceExclusion.method}. Named: ` +
    `${summary.dominanceExclusion.excluded.join(', ') || '(none)'}.`
  );
  lines.push('');

  if (best) {
    lines.push('## Recommendation');
    lines.push('');
    // VERDICT-1: the guard's own verdict, stated explicitly on the PASS path too — a reader
    // seeing a named "best" geometry below could otherwise not tell whether it cleared LAB-16's
    // ranking-validity gate or was simply array position 0 of an unordered tie, since only the
    // FAILURE branch (below) used to narrate the guard at all. A verdict shown only on failure
    // is indistinguishable from a guard that never ran.
    lines.push(
      `> **LAB-16 ranking gate: PASSED** — \`fanWidthXaDeg\` cleared the top-1 cut over all ` +
      `${summary.geometryCount} characterised geometries (${summary.fanWidthRankingGuard.distinctCount} ` +
      `distinct values, boundary ambiguity ${fmt(summary.fanWidthRankingGuard.boundaryAmbiguity, 2)}x). The ` +
      'recommendation below is a validated top-1, not an arbitrary array position.'
    );
    lines.push('');
    // RETIRE-ALL §2: provenance, when available (see main()'s --geometryOrigin). Not silently
    // omitted when unavailable — the reader is told the question wasn't answerable, not left to
    // assume it was.
    if (summary.bestGeometryOrigin) {
      const rankInPool = summary.geometries.filter((g) => g.fanWidthXaDeg !== null).findIndex((g) => g.geometryKey === best.geometryKey) + 1;
      const originText = summary.bestGeometryOrigin === 'both' ? 'both the fan-width AND cradle selection halves'
        : summary.bestGeometryOrigin === 'fanWidth' ? 'the fan-width selection half'
        : summary.bestGeometryOrigin === 'cradle' ? 'the CRADLE selection half only — NOT the fan-width half'
        : 'neither recorded selection half (unrecognised geometryKey against the supplied origin file)';
      lines.push(
        `> **Provenance (RETIRE-ALL §2):** this geometry entered Stage B's 24-candidate pool via ` +
        `${originText}. Its fan-width rank among the ${summary.geometryCount} characterised geometries ` +
        `is **#${rankInPool} of ${summary.geometryCount}** (highest measured, by construction — this is ` +
        `what "best" means here). ${summary.bestGeometryOrigin === 'cradle'
          ? 'It is named "best on fan width" despite having entered the pool through the now-withdrawn ' +
            'cradle selection (RETIRE-ALL §1: unresolvable at this budget) — its own fan width was high ' +
            'enough that this does not look like a spurious pick, but the SELECTION MECHANISM that put it ' +
            'in the candidate pool is not one this file stands behind any more.'
          : 'It would have entered the candidate pool on fan width alone, independent of the withdrawn cradle selection.'}`
      );
    } else {
      lines.push(
        '> **Provenance (RETIRE-ALL §2):** not available for this run — regenerate with ' +
        '`--geometryOrigin <stage-A-ranking.json>` to annotate which selection half this geometry ' +
        'entered the candidate pool through (see RETIRE-ALL §1).'
      );
    }
    lines.push('');
    lines.push(
      `**Machine #2 default flipper**: rest angle **${best.geometry.restAngleDeg}°**, active angle ` +
      `**${best.geometry.activeAngleDeg}°** (sweep arc ${best.geometry.activeAngleDeg - best.geometry.restAngleDeg}°), ` +
      `sweep **${best.geometry.upMs} ms**, ω-profile **${best.geometry.omegaProfile}**, collision radius ` +
      `**${best.geometry.radius} m**, restitution **${best.geometry.restitution}**.`
    );
    lines.push('');
    // RETIRE-ALL §4: the justification no longer cites timing sensitivity or a ceiling that
    // never bound — RETIRE-ALL's own instruction where a justification loses part of its
    // reason: say the recommendation rests on fan width alone, rather than inventing a
    // replacement rationale. The cradle rate stays (RETIRE-ALL §5: keep, with its event count),
    // now stated with the count attached rather than as a bare percentage.
    lines.push(
      `Justification: of the ${summary.geometryCount} geometries characterised, this one has the widest ` +
      `measured shot fan (P95−P5 of shot-line angle over the full timing sweep) at **${fmt(best.fanWidthXaDeg, 1)}°** ` +
      `— the recommendation rests on fan width alone (timing sensitivity is retired, see RETIRE-ALL §4 above; ` +
      `no replacement timing rationale is substituted for it). Alongside: a cradle rate of ` +
      `**${best.cradleRateM ? fmtMeasured(best.cradleRateM) : '—'}** (fraction of held-active trials settling ` +
      `within 1.5s — the "feels heavy" number, thin at this event count), and a vo/vi-vs-hs gradient of ` +
      `**${fmt(best.voViGradientPerHs, 3)} per unit hs** (positive means tip contact returns more energy than base ` +
      `contact, i.e. the ball rewards a good hit rather than saturating everywhere).`
    );
    lines.push('');
  } else if (!summary.fanWidthRankingGuard.ok) {
    lines.push('## Recommendation');
    lines.push('');
    lines.push(
      `> ⚠ **LAB-16 ranking gate: FAILED** — \`fanWidthXaDeg\` cannot rank the ${summary.fanWidthRankingGuard.n} ` +
      `characterised geometries — ${summary.fanWidthRankingGuard.reason}. No "best" geometry is named; picking ` +
      'array position 0 of an unordered tie would be exactly LAB-16\'s E3-P1 mistake repeated here.'
    );
    lines.push('');
  } else {
    lines.push('## Recommendation');
    lines.push('');
    lines.push('No geometry has a valid fan-width measurement — see `geometries` (empty of non-null fanWidthXaDeg) in the JSON summary.');
    lines.push('');
  }

  lines.push('## Transfer function');
  lines.push('');
  // GUARD-MIGRATE (CUT-1 spec §7, item #5): sorted by SAMPLE COUNT (`n`), not by an estimated
  // value — a bin with more trials has no sampling error advantage over one with fewer in the
  // relevant sense, so this is a display order, not a cut, and does not go through
  // `selectTopN`. Said plainly rather than left to be inferred from "best-populated".
  lines.push(`Binned \`(hs x phase x vi x ai) -> (vo, ao)\` table (${summary.transferFunction.bins.hs} x ` +
    `${summary.transferFunction.bins.phase.length} x ${summary.transferFunction.bins.vi.count} x ` +
    `${summary.transferFunction.bins.ai.count} bins), ${summary.transferFunction.table.length} populated bins ` +
    `out of a possible ${summary.transferFunction.bins.hs * summary.transferFunction.bins.phase.length * summary.transferFunction.bins.vi.count * summary.transferFunction.bins.ai.count} — ` +
    `full table in the JSON summary; the ${Math.min(20, summary.transferFunction.table.length)} bins with the most ` +
    `trials (sorted by sample count \`n\`, not a ranking of any estimated value — no cut is being claimed here):`);
  lines.push('');
  lines.push('| hs bin | phase | vi bin (m/s) | ai bin (deg) | n | vo mean±sd | ao mean±sd |');
  lines.push('|---|---|---|---|---|---|---|');
  for (const b of summary.transferFunction.table.slice(0, 20)) {
    lines.push(
      `| [${b.hsRange[0].toFixed(1)},${b.hsRange[1].toFixed(1)}) | ${b.phase} | [${b.viRange[0].toFixed(1)},${b.viRange[1].toFixed(1)}) | ` +
      `[${b.aiRange[0].toFixed(0)},${b.aiRange[1].toFixed(0)}) | ${b.n} | ${fmt(b.voMean)}±${fmt(b.voSd)} | ${fmt(b.aoMean, 1)}±${fmt(b.aoSd, 1)} |`
    );
  }
  lines.push('');
  return lines.join('\n');
}

main().catch((err) => {
  console.error(JSON.stringify({ ok: false, error: String(err?.stack ?? err) }));
  process.exitCode = 1;
});
